/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./../components2/HelloWorld2 copy.vue')['default']
    Hello: typeof import('./../components2/Hello.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HelloWorld2: typeof import('./../components2/HelloWorld2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./../components/Table.vue')['default']
    Table2: typeof import('./../components/Table2.vue')['default']
  }
}
